assn/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oh.urls')),
]

oh/urls.py
from django.urls import path


from . import views

urlpatterns = [
	path('',views.home,name='home'),
	path('add/',views.addcity,name='add-city'),
	path('ajax/load-states/', views.load_states, name='ajax_load_states'),
	path('ajax/load-districts/', views.load_districts, name='ajax_load_districts'),
	path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
	]

oh/models.py
from django.db import models

# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class District(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class City(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Data(models.Model):
    name = models.CharField(max_length=30)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

oh/forms.py
from django import forms
from .models import *

class CityForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = "__all__"


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)



        self.fields['state'].queryset = State.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['state'].queryset = State.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk and self.instance.country:
            self.fields['state'].queryset = self.instance.country.state_set.order_by('name')


        self.fields['district'].queryset = State.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['district'].queryset = District.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk and self.instance.state:
            self.fields['district'].queryset = self.instance.state.district_set.order_by('name')

        self.fields['city'].queryset = State.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['city'].queryset = City.objects.filter(
                    district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.district:
            self.fields['city'].queryset = self.instance.district.city_set.order_by(
                'name')

oh/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *


# Create your views here.
def home(request):
	all_data = Data.objects.all
	context = {'all_data':all_data,}		
	return render(request,'home.html',context)

def addcity(request):
	form = CityForm()
	if request.method =='POST':
		form = CityForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home')
	context = {'form':form,}		
	return render(request,'cityform.html',context)

def load_states(request):
    country_id = request.GET.get('country')
    states = State.objects.filter(country_id=country_id).order_by('name')
    context = {
    'states': states,
    }
    return render(request, 'state_dropdown.html', context)


def load_districts(request):
    state_id = request.GET.get('state')
    districts = District.objects.filter(state_id=state_id).order_by('name')
    context = {
    'districts': districts,
    }
    return render(request, 'district_dropdown.html', context)


def load_cities(request):
    district_id = request.GET.get('district')
    cities = City.objects.filter(district_id=district_id).order_by('name')
    context = {
    'cities': cities,
    }
    return render(request, 'city_dropdown.html', context)

templates/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple City database{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  </head>
  <body>
    <h1>Database</h1>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/city_dropdown.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/cityform.html
{% extends 'base.html'%}
{% block content %}
<form method="post" id="CityForm" data-states-url="{% url 'ajax_load_states' %}">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    
    <button type="submit" value ='Add City'>Save</button>
    <a href="{% url 'home'%}">Back</a>
    
</form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_country").change(function () {
      var url = $("#CityForm").attr("data-states-url");  
      var countryId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'country': countryId       
        },
        success: function (data) {  
          $("#id_state").html(data);  
        }
      });
    });

    $("#id_state").change(function () { 
    
    var stateId = $(this).val(); 

      $.ajax({ 
        url: '{% url 'ajax_load_districts' %}', 
        data: {
          'state': stateId 
        },
        success: function (data) { 
          $("#id_district").html(
            data); 
        }
      });
    });


    $("#id_district").change(function () { 
    
    var districtId = $(this).val(); 

      $.ajax({ 
        url: '{% url 'ajax_load_cities' %}', 
        data: {
          'district': districtId 
        },
        success: function (data) { 
          $("#id_city").html(
            data); 
        }
      });
    });
  </script>

{% endblock %}

templates/district_dropdown.html
<option value="">---------</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}

templates/home.html
{% extends 'base.html'%}
{% block content %}

 <h2> Our City Database</h2>

  <p>
    <a href="{% url 'add-city' %}">Add Data</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Country</th>
        <th>State</th>
        <th>District</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      {% for data in all_data %}
        <tr>
          <td>{{ data.name }}</td>
          <td>{{ data.country.name }}</td>
          <td>{{ data.state.name }}</td>
          <td>{{ data.district.name }}</td>
          <td>{{ data.city.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No data in the database. <a href="{% url 'add-city' %}">Add the first data here</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/state_dropdown.html
<option value="">---------</option>
{% for state in states %}
<option value="{{ state.pk }}">{{ state.name }}</option>
{% endfor %}